### ISSUE TITLE
Fetching Colletion Image does not work

### ISSUE THREAD

**Issue by magic-77** [Shopify/graphql-js-client#104]
I'm building an Shopify Ionic 3 App using the Storefront API.
Fetching ID and Title works. But trying to access Image it fails.

Using "GraphiQL" with this Query

    {
      shop {
        collections(first: 1) {
          edges {
            node {
              id
              title
              handle
              image {
                originalSrc
              }
            }
          }
          pageInfo {
            hasNextPage
          }
        }
      }
    }

will Result with

    {
      "data": {
        "shop": {
          "collections": {
            "edges": [
              {
                "node": {
                  "id": "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzM2NTUwNjY5OQ==",
                  "title": "Snacks",
                  "handle": "snacks-co",
                  "image": {
                    "originalSrc": "https://cdn.shopify.com/s/files/1/2262/0831/collections/Snacks_Collection.jpg?v=1524511173"
                  }
                }
              }
            ],
            "pageInfo": {
              "hasNextPage": true
            }
          }
        }
      }
    }

Using "graphql-js-client" with Ionic 3, Collection Image is not available.

    // Service Provider Function
    getCollectionsWithImage() {
      let query = this.client.query((root) => {
        root.add('shop', (shop) => {
          shop.addConnection('collections', {args: {first: 16}}, (collection) => {
            collection.add('id');
            collection.add('title');

            // THIS does not work
            // collection.add('image', {args: {first: 1}}, (image) => {
            //     image.add('originalSrc');
            // })

           // THIS does not work
            // collection.addConnection('image', {args: {first: 1}}, (image) => {
            //     image.add('originalSrc');
            // })                  
           })
        })
      });

      return this.client.send(query).then(({model, data}) => {
        return model.shop.collections;
      });
    }

Do you have any Idea?

**Comment by minasmart** [comment]
Image doesn’t take a first arg on collection. To match your original query, there are no options provided to image. 

```javascript
collection.add(‘image’, (image) => {
  image.add(‘originalSrc’);
});
```

That is equivalent to your original query.

**Comment by magic-77** [comment]
Using your code results in
```
ERROR Error: Uncaught (in promise): Error: No field of name "originalSrc" found on type "Image" in schema
```

**Comment by minasmart** [comment]
We didn’t publish a typed.ts. Whatever you’re using is likely third party. If you [look at the docs for the image type](https://help.shopify.com/api/storefront-api/reference/object/image) `originalSrc` is definitely an available field.

**Comment by magic-77** [comment]
@minasmart "Introspecting Query" sounds like to build a Space Ship, right now for me. I thought that Shopify Storefront API is unified and Fields like Collections gives me the standard key/values back.

**Comment by minasmart** [comment]
I’m not sure I understand what you’re saying.

**Comment by magic-77** [comment]
@minasmart I don't understand why i need to run an "Introspection Query".

**Comment by magic-77** [comment]
Ok got it! Reading some tutorials about Introspection Query and running against the Storefront API now i got all Nodes i need. Now it works with Collection Images too.
Have many thanks for your help
