### ISSUE TITLE
Not handling 'text/html' Content-Type responses

### ISSUE THREAD

**Issue by camerondubas** [Shopify/graphql-js-client#107]
Hey all 👋 

### Scenario:

The 403 Forbidden response from the Shopify Graphql API returns a `text/html` Content-Type. Currently the `httpFetcher` always runs `response.json()` regardless of Content-Type. This causes a  `Syntax Error: Unexpected end of JSON input.` on these 403s

### Proposed Solution:

Detect content-type by looking at the response headers, and run the appropriate method to parse the response body, a simple implementation of this would look similar to this update to the `httpFetcher`:

```
export default function httpFetcher(url, options = {}) {
  return function fetcher(graphQLParams) {
    return fetch(url, {
      body: JSON.stringify(graphQLParams),
      method: 'POST',
      mode: 'cors',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        ...options.headers
      }
    }).then((response) => {
      const contentType = response.headers.get('content-type');

      if (contentType.includes('application/json')) {
        return _handleJSONResponse(response);
      }

      return _handleTextResponse(response);
    });
  };
}
```

where `_handleJSONResponse` and `_handleTextResponse` would have the `response.json()` and `response.text()` calls respectively, as well as wrapping the the body from`text/html` responses in an object, so that the return value of `httpFetcher` is always an object.

This is just a suggested solution, to get the conversation started on how to handle these non-json responses. I'd love to hear any other possible ways to handle this.

Thanks!

**Comment by swalkinshaw** [comment]
This is a good idea @camerondubas. One issue though is that `graphql-js-client` is supposed to be generic to any GraphQL API and that 403 forbidden response is a Shopify specific problem.

Maybe we could implement this on js-buy-sdk instead?

Although I could also see how it would fine to handle this situation for any API as well.

**Comment by camerondubas** [comment]
Unfortunately I don't think this can be handled by the `js-buy-sdk` as the error has already occurred by the time the buy sdk has any control. All that the buy sdk receives is the `Syntax Error: Unexpected end of JSON input.` error messaging.

I suppose the buy sdk could check for this error message, and handle it in some way, but the actual content of the response body is lost (albeit in this specific case the response body is an empty text object anyway).

You mention that `graphql-js-client` should be generic and that this is specific to Shopfiy. Does that indicate that Shopify's implementation flawed here, and that the real "fix" should be in  the API itself? Simply returning `Content-Type: application/json` would clear up this issue altogether.

**Comment by swalkinshaw** [comment]
> Does that indicate that Shopify's implementation is flawed here, and that the real "fix" should be in  the API itself? Simply returning `Content-Type: application/json` would clear up this issue altogether.

I work for Shopify, but my personal opinion is yes it's flawed. I'd expect a JSON based API to always return JSON. It's something that's come up over time, but I don't know if it has to stay that way for some legacy reason or not.

**Comment by camerondubas** [comment]
Ya, It's totally reasonable that Shopify may need to continue sending the `text/html` 403s for legacy reasons.

With this in mind, how do you feel about a similar solution to the one I suggested initially? 

This would have no effect on typical `application/json` requests, which as you mention _should_ be every request in a JSON based API. This means that the `graphql-js-client` would still remain generic to GraphQL APIs that always send JSON payloads.

**Comment by swalkinshaw** [comment]
I think it sounds good. A PR would be welcomed 😄
