### ISSUE TITLE
[Feature Request]: Typescript Types for Shopify GraphQL Schema

### ISSUE THREAD

**Issue by damienwebdev** [Shopify/graphql-js-client#112]
I'm not sure if this is in the scope of this repo, or another, so I apologize if this is in the wrong spot.

Is it possible to get all of typescript types of the GraphQL Storefront API?

E.g.

```
interface GetAllProductsResponse {
  shop?: {
    products?: ProductEdge[]
  }
}

interface ProductEdge {
  node: Node
}

interface ProductNode {
  id?: string;
  title?: string;
}
```

Currently, I'm defining these types as I go along based on the docs I'm reading [here](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/queryroot).

Is there a standard set of these for typescript that is either:

1. Published internally at shopify and potentially published as Open Source
2. Published open source already and I can't seem to find them

Finally, if a package doesn't exist, is this something that would be valuable, or am I proposing a solution to a non-existant problem?

**Comment by minasmart** [comment]
It looks like there is tooling that exists to turn a graphql schema into a set of typescript types:

https://github.com/dangcuuson/graphql-schema-typescript

That said: this is not the repo for it. This is a generic graphql client with no coupling to Shopify's graphql API.
