### ISSUE TITLE
CORB errors

### ISSUE THREAD

**Issue by benbonnet** [Shopify/graphql-js-client#113]
Hello, while requesting client side, I'm hitting the following :

`Cross-Origin Read Blocking (CORB) blocked cross-origin...`

While using `"Content-Type": "application/json"`, in order to be able to use the defaults `query` and `variables`that graphql usually provide.

This is basically what the graphiql page use (https://help.shopify.com/en/api/graphiql)

It does work ok while using "Content-Type": "application/graphql". But in that case, it is not possible to use query/variables capabilities

Is the behaviour expected; or is there something to solve ?

Thx for your help

**Comment by minasmart** [comment]
Can you show me something in terms of code, configuration, or what end point your request is hitting? Cross origin blocking is a function of the browser, so I think I need more context to answer this.

**Comment by benbonnet** [comment]
hello, sorry for bothering on that one. Using fetch, the json payload had to be stringified
