### ISSUE TITLE
Querying existing checkout 

### ISSUE THREAD

**Issue by HAWRAF** [Shopify/graphql-js-client#120]
Hi, I'm having trouble determining how to implement this kind of syntax:
{  node(id: "your_id_here") {
    id
    **... on Checkout** {
       
   }
}

I've successfully queried the checkout node, and have tried a bunch of methods to try to include the checkout object in the results, but it keeps giving me errors.  So far the easiest way for me to get around this has been just to send an empty mutation to the 'checkoutLineItemsAdd' instead, but this obviously feels wrong.

**Comment by minasmart** [comment]
Do you mean with using the query builder syntax? If so, you could do:

```javascript
const query = client.query((root) => {
  root.add('node', {args: {id: "some-checkout-id"}}, (node) => {
    node.add('id');
    node.addInlineFragmentOn('Checkout', (product) => {
      product.add('total');
    });
  });
});
```

**Comment by HAWRAF** [comment]
I think 'addInlineFragmentOn' is exactly what I'm looking for.  Thanks!

**Comment by minasmart** [comment]
Great!
