### ISSUE TITLE
Accessing available shipping rates

### ISSUE THREAD

**Issue by Jimtattersall** [Shopify/graphql-js-client#129]
Hi there, i'm struggling to access the available shipping rates through the query builder. When I try to add the availableShippingRates as a connection or field it fails. Any help would be appreciated. 

``` js
client.graphQLClient.query(root => {
    root.add('node', { args: { id: cartId} }, node => {
        node.addInlineFragmentOn('Checkout', checkout => {
            checkout.add('availableShippingRates')
        })
    })
})
```

**Comment by minasmart** [comment]
`availableShippingRates` is an `OBJECT` type and not a `SCALAR` type. This means that you're required to provide selections. Take a look at [the storefront api docs on the available shipping rates type](https://help.shopify.com/en/api/storefront-api/reference/object/availableshippingrates) to see what fields are available.

**Comment by kneeki** [comment]
Hey @minasmart,

My apologies for the ressurection but I'm unable to find any documentation on how to use this library effectively. If you happen to have any links to videos or documentation (other than [this](https://www.npmjs.com/package/shopify-buy)) it would be **greatly appreciated**!

```typescript
const query = this.client.graphQLClient.query((root) => {
  root.add('node', { args: {id: checkout_id} }, (node) => {
    node.add('id');
    node.addInlineFragmentOn('Checkout', (checkout) => {
      checkout.add('totalPrice');
      checkout.addConnection('availableShippingRates', (rate) => {
        rate.add('title');
      });
    });
  });
});

return this.client.graphQLClient.send(query).then(({ model, data }) => {
  return data;
});
```

gives me the error: 

**ERROR Error: Uncaught (in promise): Error: No field of name "pageInfo" found on type "AvailableShippingRates" in schema
Error: No field of name "pageInfo" found on type "AvailableShippingRates" in schema**

---------

To be fair, I'm guessing. I don't know when I should be using `addInlineFragmentOn`, `addConnection`, or any other provided function. For some reason [the documentation](https://shopify.github.io/graphql-js-client/SelectionSetBuilder.html) is breaking me. Maybe I need a good nights sleep after reading it. -.-
