### ISSUE TITLE
GraphQL Bug?

### ISSUE THREAD

**Issue by kennandavison** [Shopify/graphql-js-client#137]
Hi - is maxVariantPrice being different than price intended?

<img width="811" alt="Screen Shot 2020-05-02 at 3 57 46 PM" src="https://user-images.githubusercontent.com/12569707/80894192-db8dc480-8c8d-11ea-9fb0-90f062e11f36.png">

**Comment by swalkinshaw** [comment]
This repository isn't Shopify specific so it's not the right place for issues related to our APIs.
