### ISSUE TITLE
query/mutation of giftCards not apparent

### ISSUE THREAD

**Issue by nacmonad** [Shopify/graphql-js-client#161]
Following document for graphql mutation createGiftCard, or query giftCards (https://shopify.dev/api/examples/gift-cards).  
It appears this feature is not even available ?

`{"errors":[{"message":"GiftCardCreateInput isn't a defined input type (on $input)","locations":[{"line":1,"column":25}],"path":["mutation giftCardCreate"],"extensions":{"code":"variableRequiresValidType","typeName":"GiftCardCreateInput","variableName":"input"}},{"message":"Field 'giftCardCreate' doesn't exist on type 'Mutation'","locations":[{"line":2,"column":3}],"path":["mutation giftCardCreate","giftCardCreate"],"extensions":{"code":"undefinedField","typeName":"Mutation","fieldName":"giftCardCreate"}},{"message":"Variable $input is declared by giftCardCreate but not used","locations":[{"line":1,"column":1}],"path":["mutation giftCardCreate"],"extensions":{"code":"variableNotUsed","variableName":"input"}}]}`

`{"errors":[{"message":"Field 'giftCards' doesn't exist on type 'QueryRoot'","locations":[{"line":2,"column":3}],"path":["query","giftCards"],"extensions":{"code":"undefinedField","typeName":"QueryRoot","fieldName":"giftCards"}}]}`

**Comment by swalkinshaw** [comment]
This repository is for a generic GraphQL JS client and is not specific to Shopify's APIs. For Shopify support, you can use any of the community links provided on https://shopify.dev/ such as our [forums](https://community.shopify.com/c/shopify-discussion/ct-p/shopify-discussion).

But yes, there is a [giftCardCreate](https://shopify.dev/api/admin-graphql/2021-04/mutations/giftcardcreate) mutation as of API version `2021-04` (my guess is you're using an older version?).
