### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by bcowell** [Shopify/graphql-js-client#94]
Hi, kinda new to this. I can include the source if it's more helpful, but I basically copied the readme.
Running into this when I run my vue app on localhost.
```
Nuxt.js Error:

ReferenceError: fetch is not defined
    at Client.fetcher (/Users/bcowell/Documents/GitHub/vue-store/node_modules/graphql-js-client/index.js:1709:12)
    at Client.send (/Users/bcowell/Documents/GitHub/vue-store/node_modules/graphql-js-client/index.js:1892:19)
    at module.exports.__webpack_exports__.default (middleware/shopify.js:27:10)
    at promisify (.nuxt/utils.js:117:14)
    at middlewareSeries (.nuxt/utils.js:97:9)
    at Object._callee$ (.nuxt/server.js:81:27)
    at tryCatch (/Users/bcowell/Documents/GitHub/vue-store/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/bcowell/Documents/GitHub/vue-store/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/bcowell/Documents/GitHub/vue-store/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:816:13
    at <anonymous>
```

**Comment by juaguz** [comment]
that is because probably, you are trying to fetch data in the asyncData an this fails because this happens in the server side and you dont have the fetch funcition in that scope, if you try it in the created or mounted functions it will work

**Comment by minasmart** [comment]
yeah, it's difficult to make the package itself isomorphic around this function. The best approach right now would be to define your own fetcher, or do something like `globals.fetch = require('node-fetch');`

If you want to define your own fetcher, the [Client constructor](https://github.com/Shopify/graphql-js-client/blob/master/src/client.js#L31) takes a `fetcher` function. You could take the code from `[http-fetcher.js](https://github.com/Shopify/graphql-js-client/blob/master/src/http-fetcher.js)` and rewrite that to use node fetch, or any other network library available server side.

An example using node-fetch would look like:

```javascript
import fetch from 'node-fetch';

export default function httpFetcher(url, options = {}) {
  return function fetcher(graphQLParams) {
    return fetch(url, {
      body: JSON.stringify(graphQLParams),
      method: 'POST',
      mode: 'cors',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        ...options.headers
      }
    }).then((response) => response.json());
  };
}
```
Assuming you have `node-fetch` in your package.json.

**Comment by maziarz** [comment]
@juaguz, i tried this in mounted and created, the problem still persists.

**Comment by maziarz** [comment]
@minasmart How is the fetcher injected into the Client constructor (1.0.0-alpha.12)? I am having similar problems in a server-side rendered application.

**Comment by minasmart** [comment]
@maziarz are you asking about js buy or the graphql client? In the graphql client, the consturctor takes an option called `fetcher`, so like `new Client(typeBundle, {fetcher: () => { ... }})`

**Comment by maziarz** [comment]
@minasmart, but this has nothing to do with the Client constructor in shopify-buy?

**Comment by maziarz** [comment]
@minasmart, i get the error related to the `shopify-buy`, i never instantiate `graphql-js-client` manually.

**Comment by minasmart** [comment]
maybe open an issue on `js-buy-sdk` specifically about the problem you're having?

**Comment by maziarz** [comment]
I'd be more than glad to that. Would it make sense to reference those two issues as they are essentially the same just with different origins?
