### ISSUE TITLE
Issue with webURL missing checkout.shopify.com?

### ISSUE THREAD

**Issue by youanden** [Shopify/graphql-js-client#95]
Seems like checkout object returned when adding line items is returning a malformed url.

For example:
```https:///{shopifyStoreId}/checkouts/{checkoutId}?key={key}```

It has been doing that for approximately 3 hours now.

I know this comes with the beta but it seems like the API is stable and I checked the graphql response. It came directly from the API and wasn't modified by the client.

Let me know if you need me to provide more info. I'd be happy to submit a bug report with actual cart IDs, request query, etc.

**Comment by swalkinshaw** [comment]
See https://github.com/Shopify/js-buy-sdk/issues/407#issuecomment-327498326
